const data = {
  li: "linkedin.com/in/sulaiman-sudirman",
  linkedin: "linkedin.com/in/sulaiman-sudirman",
  gh: "github.com/natsu90",
  github: "github.com/natsu90",
  so: "stackoverflow.com/u/1109004",
  stackoverflow: "stackoverflow.com/u/1109004",
  blog: "sulaiman.dev",
  fb: "facebook.com/mohd.sulaiman.sudirman",
  facebook: "facebook.com/mohd.sulaiman.sudirman",
  ig: "instagram.com/mohd.sulaiman.sudirman",
  instagram: "instagram.com/mohd.sulaiman.sudirman",
  goodreads: "goodreads.com/sulaiman_sudirman",
  twitter: "twitter.com/natsu90",
  spotify: "open.spotify.com/user/natsu901",
  nl: "nomadlist.com/@natsu90",
  nomadlist: "nomadlist.com/@natsu90",
  youtube: "youtube.com/user/natsu902",
  yt: "youtube.com/user/natsu902",
  pinterest: "pinterest.com/natsu90",
  applemusic: "music.apple.com/profile/natsu90",
  reddit: "reddit.com/user/natsu901",
  hn: "news.ycombinator.com/user?id=natsu90",
  source: "github.com/natsu90/url-shortener",
  ge15: "docs.google.com/forms/d/e/1FAIpQLSezFjJjHDq13BFXdWvf8oX9SErWyPaFxRAKvEL0T3zsRME9vQ/viewform",
}
